# Base options
baseURL: "https://tilde.town/~resir014/"
languageCode: "en-us"
title: "~resir014"

# Pygments
pygmentsStyle: "native"

# Menu options
menu:
  main:
    - name: "photography"
      weight: -110
      identifier: "photography"
      url: "/photography/"
    - name: "music"
      weight: -100
      identifier: "music"
      url: "/music/"
    - name: "timeless games"
      weight: -90
      identifier: "timeless-games"
      url: "/timeless-games/"
    - name: "stuff"
      weight: -80
      identifier: "etc"
      url: "/etc/"
    - name: "tildetv"
      weight: -70
      identifier: "tildetv"
      url: "/tildetv/"

# Custom params
params:
  subtitle: "Web developer based in Jakarta, Indonesia."
