#!/bin/bash
#
# Script to perform a Hugo deploy to a public HTML directory.
#

HUGO_DEST="$HOME/public_html"

echo -e "Deploy started."

# Step 1: build Hugo
echo -e "\nBuilding Hugo site to ${HUGO_DEST}..."
hugo -d $HUGO_DEST

# Test if Hugo build is successful
RESULT_HUGO=$?
if [ $RESULT_HUGO -ne 0 ]; then
  # Exit if build failed
  echo -e "\nDeployment failed: Hugo build failed."
  exit 1
fi

echo -e "\nHugo build successful."
